server:
  port: 8730

spring:
  datasource:
    username: root
    password: Aa12345
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.230.129:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto