server:
  port: 8000

spring:
  application:
    name: cloud-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: product_route
          uri: lb://cloud-gulimall-product
#          uri: http://localhost:8730
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
#          uri: lb://gulimall-coupon
          uri: http://localhost:8720
          predicates:
            - Path=/coupon/SmsCoupon/** # 断言，路径相匹配的进行路由
#        - id: payment_route2
          #          uri: http://localhost:8700
#          uri: lb://CLOUD-PAYMENT-PRODUCER
#          predicates:
#            - Path=/payment/lb/** #断言,路径相匹配的进行路由
    #            - After=2022-08-04T01:07:29.835+08:00[Asia/Shanghai] 在某个时间后才能访问。Before/Between
        - id: renren_route
          uri: lb://renren-fast
#          uri: http://localhost:8080
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}